# Azure Databricks Build Pipeline
# azure-pipelines.yml

trigger:
- release

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python3'

- script: |
    pip install databricks-cli
  displayName: 'Install databricks CLI'

- task: configuredatabricks@0
  inputs:
    url: 'https://adb-1677014537118923.3.azuredatabricks.net/'
    token: 'dapia989e78acff2e6dfbec256c37b75b41c-2'


- task: startcluster@0
  inputs:
    clusterid: '0305-150117-sue716'

- task: compileinstalljar@0
  inputs:
    clusterid: '0305-150117-sue716'
    workingDirectory: '$(Build.SourcesDirectory)'
    packageName: 'hive-analytics-lib'
    packageVersion: '1.0'
    scalaVersion: '2.12.7'

    
